using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.AdditionalShuttleControl;

[GenerateTypedNameReferences]
public sealed partial class AdditionalShuttleControlRotateToPoint : BoxContainer
{
    public AdditionalShuttleControlRotateToPoint()
    {
        RobustXamlLoader.Load(this);
    }
}

